### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by joy-void-joy** [jamiepine/prismix#31]
Hi,

This repository is missing a license. This means that it is currently under the "All right reserved" license.
Is that intended? If it is not, could you add a license to your code, such as the MIT license or the one of your choice?

Thanks again :)

**Comment by jamiepine** [comment]
added a license! sorry about that

https://github.com/jamiepine/prismix/blob/master/LICENCE

**Comment by joy-void-joy** [comment]
Thanks!

For information, this license is not the same as the one in package.json 's license field, in case you missed it

Thanks again, and thanks for this package!
