### ISSUE TITLE
No releases?!

### ISSUE THREAD

**Issue by Chosey98** [jamiepine/prismix#42]
I see there is pull requests that gets opened and merged and solves alot of stuff like the @db.<Type> fix but apparently nothing gets updated on NPM for some reason cause there is no new releases being created @jamiepine so please relink npm to the github repo releases

**Comment by jamiepine** [comment]
just pushed 1.0.22

**Comment by Chosey98** [comment]
Thanks for responding and actually releasing the version
Just a quick note the version on the package.json needs to be changed
and a quick question: I know that you have the postInstall which runs npm run build which is a great thing since the run for the prismix for stuff like calling in the cli `prismix` runs from the built version the `dist` but the problem is I'm not able to even install it since I already have prisma and prismix running parallel together as I have two schemas one uses a schema.prisma for a database and the other uses another database while using prismix

Can you tell me if it's possible to use prismix for both dbs and disregard prisma in order to be able to build or any other way to mitigate the build error?
