### ISSUE TITLE
Not recognising model in base.schema

### ISSUE THREAD

**Issue by webnoob** [jamiepine/prismix#5]
My `prisma/base.schema`:
```
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["orderByAggregateGroup", "selectRelationCount"]
}

model Company {
  id            Int           @id @default(autoincrement())
  createdDate   DateTime      @default(now())
  updatedDate   DateTime?
  name          String
}
```
My extended schema `src/modules/job-group/prisma/model.schema.prisma`
```
model JobGroup {
  id          Int     @id @default(autoincrement())
  createdDate DateTime  @default(now())
  updatedDate DateTime?

  company Company   @relation(fields: [companyId], references: [id])
  companyId Int

  user   User @relation(fields: [userId], references: [id])
  userId Int
}
```
My config:
```
{
  "mixers": [
    {
      "input": [
        "./prisma/base.prisma",
        "./src/modules/job-group/prisma/model.schema.prisma"
      ]
    }
  ]
}
```

Running `npx prismix` and getting:
![image](https://user-images.githubusercontent.com/10404747/128939990-b5a2bad4-ad2e-4f99-8416-f626f1b1b89b.png)

Note: If I change either of the paths in my config, it throws an error that they don't exist so it's reading them properly.

This seems to be the most basic thing this tool does - what am I doing wrong for it not to be working?

**Comment by jamiepine** [comment]
It looks like you're missing an alias `Company` model in your extended schema. Without a local reference to it, Prisma will not be able to compile the schema. Prismix uses the Prisma SDK to parse each schema individually before merging models at field level.

```prisma
model JobGroup {
  id          Int     @id @default(autoincrement())
  createdDate DateTime  @default(now())
  updatedDate DateTime?

  company Company   @relation(fields: [companyId], references: [id])
  companyId Int

  user   User @relation(fields: [userId], references: [id])
  userId Int
}

model Company {
  id            Int           @id @default(autoincrement())
}
```

This is in the readme, but perhaps I could make it clearer? Sorry about that!

**Comment by webnoob** [comment]
Ahhh, I see it now:

> In order for posts to relate to accounts we can define an empty model to represent the account.

It didn't register that this is what was meant when I read it but it is clear. Thanks for the response, I appreciate it.
